In [1]:
import numpy as np

[1 2 3 4]


In [16]:
print("Numpy Array - 1D")
print(np.array([1,2,3,4]))
print("Numpy Array - 2D")
print(np.array([[1,2], [3,4]]))
print("Numpy Array - 3D")
print(np.array([[[1,4],[5,6]]]))

Numpy Array - 1D
[1 2 3 4]
Numpy Array - 2D
[[1 2]
 [3 4]]
Numpy Array - 3D
[[[1 4]
  [5 6]]]


In [5]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.array([1,2,3,4,5,6]).shape

(6,)

In [35]:
np.random.seed(101) 
# using this random generated array is same for everytime it runs
arr = np.random.randint(1,100,10)
arr

array([96, 12, 82, 71, 64, 88, 76, 10, 78, 41])

In [36]:
arr = arr.reshape(2,5) 
# the multiple of values provided as params must be equal to the size of the array
# here possible shapes are: 5x2, 2x5, 10x1, 1x10

In [19]:
np.zeros((2,3), int)

array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
np.ones((2,), int)

array([1, 1])

In [37]:
arr[:,0:2] = 0
arr

array([[ 0,  0, 82, 71, 64],
       [ 0,  0, 10, 78, 41]])

In [38]:
new_arr = np.copy(arr)
new_arr[:,0:2] = 5
new_arr

array([[ 5,  5, 82, 71, 64],
       [ 5,  5, 10, 78, 41]])